### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by xjoshramos** [Artifineuro/crl#4]
Is there a python version for inference.  I am able to run a forward pass with the following code. Output is shown.

For inference, is net.blobs('zero').set_data(zeros(width_test, height_test));
net.blobs('coord_canon').set_data(coord); needed?

![my](https://user-images.githubusercontent.com/4721207/33678469-a6868780-da70-11e7-88cd-a2de4fecd35f.png)

path_left = 'left.jpg'
path_right = 'right.jpg'
MODEL_FILE = 'deploy_kitti.prototxt'
PRETRAINED = 'crl.caffemodel'
left_img = cv2.imread(path_left)
right_img = cv2.imread(path_right)
caffe.set_mode_gpu()
caffe.set_device(0)
net = caffe.Net(MODEL_FILE, PRETRAINED, caffe.TEST)
left_img = cv2.resize(left_img, (net.blobs['img0'].data.shape[3],net.blobs['img0'].data.shape[2]))
right_img = cv2.resize(right_img, (net.blobs['img1'].data.shape[3],net.blobs['img1'].data.shape[2]))
left_img = left_img.astype(np.float32)
left_img = left_img.transpose((2, 0, 1))
right_img = right_img.astype(np.float32)
right_img = right_img.transpose((2, 0, 1))
net.blobs['img0'].data[...] = left_img 
net.blobs['img1'].data[...] = right_img
caffe.set_mode_gpu()
caffe.set_device(0)
disp = net.forward()
out = -disp["predict_flow2_s2"].transpose(2,3,0,1).reshape(320,1792)
img = Image.fromarray(out, 'RGB')
img.save('my.png')
img.show()

**Comment by xjoshramos** [comment]
FIXED::
![left](https://user-images.githubusercontent.com/4721207/33691881-5a42eb64-da9f-11e7-9076-82ff307075cb.jpg)

![crl](https://user-images.githubusercontent.com/4721207/33691870-49632a16-da9f-11e7-9baf-e2cd31825ff2.png)

**Comment by xjoshramos** [comment]
![crl](https://user-images.githubusercontent.com/4721207/33691994-063b3714-daa0-11e7-8ded-4c9f67e9a65b.png)

**Comment by mittalrajat** [comment]
Hey @xjoshramos How did you fix it?
